language: java
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - Z3_DIR=~/z3
    - RACKET_URL="http://www.eecs.northwestern.edu/racket/6.2.1/racket-6.2.1-x86_64-linux-ubuntu-precise.sh"

install:
  - if [[ ! -e "$RACKET_DIR/bin/racket" ]]; then
      rm -rf $RACKET_DIR;
      curl -L -o racket.sh $RACKET_URL;
      sh ./racket.sh --in-place --dest $RACKET_DIR;
    else echo "using racket from cache"; fi
  - if [[ ! -e "$Z3_DIR/build/z3" ]]; then
      rm -rf $Z3_DIR;
      git clone https://github.com/z3prover/z3.git $Z3_DIR;
      cd $Z3_DIR;
      python scripts/mk_make.py;
      cd $Z3_DIR/build;
      make -j2;
      cd $TRAVIS_BUILD_DIR;
    else echo "using z3 from cache"; fi
  - mkdir bin/
  - cp $Z3_DIR/build/z3 bin/
  - bin/z3 --version
  - cd $Z3_DIR && git rev-parse HEAD && cd $TRAVIS_BUILD_DIR

script:
  - ~/racket/bin/raco link rosette
  - ~/racket/bin/raco setup -l rosette
  - time ~/racket/bin/raco make test/all-rosette-tests.rkt
  - ~/racket/bin/raco test test/all-rosette-tests.rkt
  - time ~/racket/bin/raco make test/all-sdsl-tests.rkt
  - ~/racket/bin/raco test test/all-sdsl-tests.rkt

cache:
  directories:
    - $Z3_DIR
    - $RACKET_DIR